[package]
name = "library_updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sql-parse = "0.16.0"
tokio = { version = "1.33.0", features = ["full"] }
tokio-postgres = { version = "0.7.10", features = ["with-chrono-0_4"] }
deadpool-postgres = "0.11.0"
async-trait = "0.1.74"
chrono = "0.4.31"
futures =  "0.3.29"
reqwest = { version = "0.11.22", features = ["stream"] }
tokio-util = { version = "0.7.10", features = ["compat"] }
async-compression = { version = "0.4.4", features = ["futures-io", "gzip"] }
sentry = { version = "0.31.7", features = ["debug-images"] }
lazy_static = "1.4.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
tokio-cron-scheduler = "0.9.4"
axum = "0.6.20"
ammonia = "3.3.0"
maplit = "1.0.2"

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"]}
tower-http = { version = "0.4.4", features = ["trace"] }
