[package]
name = "library_updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sql-parse = "0.8.0"
tokio = { version = "1.21.1", features = ["full"] }
tokio-postgres = { version = "0.7.6", features = ["with-chrono-0_4"] }
deadpool-postgres = "0.10.2"
async-trait = "0.1.57"
chrono = "0.4.22"
futures =  "0.3.24"
reqwest = { version = "0.11.11", features = ["stream"] }
tokio-util = { version = "0.7.3", features = ["compat"] }
async-compression = { version = "0.3.14", features = ["futures-io", "gzip"] }
sentry = "0.27.0"
lazy_static = "1.4.0"
log = "0.4"
env_logger = "0.9.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
tokio-cron-scheduler = "0.8.1"
axum = "0.5.16"
