[package]
name = "library_updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sql-parse = "0.15.0"
tokio = { version = "1.28.2", features = ["full"] }
tokio-postgres = { version = "0.7.8", features = ["with-chrono-0_4"] }
deadpool-postgres = "0.10.5"
async-trait = "0.1.68"
chrono = "0.4.25"
futures =  "0.3.28"
reqwest = { version = "0.11.18", features = ["stream"] }
tokio-util = { version = "0.7.8", features = ["compat"] }
async-compression = { version = "0.4.0", features = ["futures-io", "gzip"] }
sentry = "0.31.3"
lazy_static = "1.4.0"
log = "0.4.18"
env_logger = "0.10.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tokio-cron-scheduler = "0.9.4"
axum = "0.6.18"
ammonia = "3.3.0"
maplit = "1.0.2"
