[package]
name = "library_updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sql-parse = "0.15.1"
tokio = { version = "1.32.0", features = ["full"] }
tokio-postgres = { version = "0.7.10", features = ["with-chrono-0_4"] }
deadpool-postgres = "0.10.5"
async-trait = "0.1.73"
chrono = "0.4.30"
futures =  "0.3.28"
reqwest = { version = "0.11.20", features = ["stream"] }
tokio-util = { version = "0.7.8", features = ["compat"] }
async-compression = { version = "0.4.3", features = ["futures-io", "gzip"] }
sentry = { version = "0.31.7", features = ["debug-images"] }
lazy_static = "1.4.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio-cron-scheduler = "0.9.4"
axum = "0.6.20"
ammonia = "3.3.0"
maplit = "1.0.2"

tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"]}
tower-http = { version = "0.4.4", features = ["trace"] }
